-- AlterEnum: Add AWAITING_PICKING and READY_TO_INVOICE to SalesOrderStatus
ALTER TYPE "SalesOrderStatus" ADD VALUE IF NOT EXISTS 'AWAITING_PICKING' AFTER 'CONFIRMED';
ALTER TYPE "SalesOrderStatus" ADD VALUE IF NOT EXISTS 'READY_TO_INVOICE' AFTER 'AWAITING_PICKING';

-- AlterTable: Add pickedAt to SalesOrder
ALTER TABLE "gdr_sales_orders" ADD COLUMN "pickedAt" TIMESTAMP(3);
